### ISSUE TITLE
ModuleNotFoundError: No module named 'Tree.core'; 'Tree' is not a package

### ISSUE THREAD

**Issue by safo-bora** [PixelwarStudio/PyFractalTree#2]
Example doesn't work . I have Python 3.6 and Tree version v0.2.3
___________

Run example:
```
from math import pi, radians as rad
from Tree.core import Tree
from PIL import Image

branches = (
    (.5, rad(-30)),
    (.6, rad(30)),
    (.4, rad(60))
)

def main():
    tree = Tree(
        pos=(0, 0, 0, -500),
        branches=branches
    )

    # Let the tree grow
    tree.grow(10)

    # Move the tree in the right position, so that the tree is completly in the image
    tree.move_in_rectangle()

    im = Image.new("RGB", tree.get_size(), (239, 239, 239))
    tree.draw_on(im, (85, 25, 0, 128, 53, 21), (0, 62, 21), 10)
    im.show()

if __name__ == '__main__':
    main()
```

**And have error:**
_Traceback (most recent call last):
  File "D:/Git/tree_test.py", line 2, in <module>
    from Tree.core import Tree
ModuleNotFoundError: No module named 'Tree.core'; 'Tree' is not a package_

**Comment by PixelwarStudio** [comment]
Did you install Tree through pip? What output gives you 'pip show Tree'? Unfortunately I can test this only on a linux machine at the moment, so I can't test a windows-specific setup.

**Comment by safo-bora** [comment]
Yes - I installed it with pip.

Now I am testing Tree on my Mac.

```
MacBook:tryTree safo$ pip show Tree
Name: Tree
Version: 0.2.3
Summary: A package for creating and drawing trees
Home-page: https://github.com/PixelwarStudio/PyTree
Author: Pixelwar
Author-email: UNKNOWN
License: MIT
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires: Pillow, svgwrite, setuptools, click
Required-by: 

```

I run the same code from example but have other error now.

```
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/safo/PycharmProjects/tryTree/123.py
Traceback (most recent call last):
  File "/Users/safo/PycharmProjects/tryTree/123.py", line 2, in <module>
    from Tree.core import Tree
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Tree/core.py", line 7, in <module>
    from Tree.draw import SUPPORTED_CANVAS
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Tree/draw.py", line 4, in <module>
    from PIL import ImageDraw
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/ImageDraw.py", line 35, in <module>
    from . import Image, ImageColor
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so, 2): Symbol not found: _clock_gettime
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/.dylibs/liblzma.5.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/.dylibs/liblzma.5.dylib
```

**Comment by safo-bora** [comment]
So ok, I tested on Python 2.7. 

My code was always the same.

Faced with error:
```

/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/safo/PycharmProjects/tryTree/123.py
Traceback (most recent call last):
  File "/Users/safo/PycharmProjects/tryTree/123.py", line 29, in <module>
    main()
  File "/Users/safo/PycharmProjects/tryTree/123.py", line 25, in main
    tree.draw_on(im, (85, 25, 0, 128, 53, 21), (0, 62, 21), 10)
TypeError: draw_on() takes at most 4 arguments (5 given)

Process finished with exit code 1
```

I did small fix:
`tree.draw_on(im, (85, 25, 0, 128, 53, 21), (0, 62, 21), 10)`
-> 
`tree.draw_on(im, (85, 25, 0, 128, 53, 21))`

And now it works - I see image with the tree created by code.

**Comment by safo-bora** [comment]
If comeback to python 3.6:

I manually reinstall all libraries from requirements.txt

```
click==6.7
sphinx_rtd_theme==0.2.4
setuptools==20.7.0
svgwrite==1.1.10
Pillow==4.2.1
```

Output:

```
MacBook:tryTree safo$ pip install --user sphinx_rtd_theme
Collecting sphinx_rtd_theme
  Using cached https://files.pythonhosted.org/packages/5d/01/f367780d51e9b353cec890257c84202a340f645d5a037b61a52c93669764/sphinx_rtd_theme-0.4.0-py2.py3-none-any.whl
Installing collected packages: sphinx-rtd-theme
Successfully installed sphinx-rtd-theme-0.4.0
MacBook:tryTree safo$ pip install --user svgwrite
Requirement already satisfied: svgwrite in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (1.1.12)
Requirement already satisfied: pyparsing>=2.0.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from svgwrite) (2.2.0)
MacBook:tryTree safo$ pip install --user Pillow
Requirement already satisfied: Pillow in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (5.1.0)
```

Error is the same:

```
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/safo/PycharmProjects/tryTree/123.py
Traceback (most recent call last):
  File "/Users/safo/PycharmProjects/tryTree/123.py", line 2, in <module>
    from Tree.core import Tree
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Tree/core.py", line 7, in <module>
    from Tree.draw import SUPPORTED_CANVAS
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Tree/draw.py", line 4, in <module>
    from PIL import ImageDraw
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/ImageDraw.py", line 35, in <module>
    from . import Image, ImageColor
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so, 2): Symbol not found: _clock_gettime
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/.dylibs/liblzma.5.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/.dylibs/liblzma.5.dylib
```

**Comment by PixelwarStudio** [comment]
I uploaded v0.2.4, hoping that will fix your issues. It seems that I forgot to release the version that the example depends on.
Edit: Try to install Tree with "pip3 install Tree" or something like this, usually pip refers to the pip version for python 2.x.x. You can check this with pip --version.

**Comment by safo-bora** [comment]
Tree has correct location

```
pip --version
pip 10.0.1 from D:\Python3.6.4\autotesting_libs\lib\site-packages\pip-10.0.1-py3.6.egg\pip (python 3.6)
```


**Windows + Python 3.6**

```
pip show Tree

Name: Tree
Version: 0.2.4
Summary: A package for creating and drawing trees
Home-page: https://github.com/PixelwarStudio/PyTree
Author: Pixelwar
Author-email: UNKNOWN
License: MIT
Location: d:\python3.6.4\autotesting_libs\lib\site-packages
Requires: Pillow, svgwrite, setuptools, click
Required-by:
```

RESULT:
```
D:\Python3.6.4\autotesting_libs\Scripts\python.exe D:/Git/tree_test.py
Traceback (most recent call last):
  File "D:/Git/tree_test.py", line 2, in <module>
    from Tree.core import Tree
ModuleNotFoundError: No module named 'Tree.core'; 'Tree' is not a package
```


______________________________________

**Windows + Python 2.7:**

RESULT:
```
C:\Python27\python.exe D:/Git/tree_test.py
Traceback (most recent call last):
  File "D:/Git/tree_test.py", line 2, in <module>
    from Tree.core import Tree
ImportError: No module named core
```

**Comment by safo-bora** [comment]
I think you have problem with sys.path usage in you project. I will try to debug and say feedback.

**Comment by PixelwarStudio** [comment]
I'm a little bit clueless, because I tested it on clean windows installation and it worked perfectly. But I used `python -m pip install Tree` instead of `pip install Tree`.

**Comment by safo-bora** [comment]
Works with python -m pip install Tree.
Maybe really something with my environment.

And also I just changed import and now it also works. So ok ticket can be closed.

Thanks!

core.py:
```
from math import pi, log, sqrt
from random import gauss
from utils import Node
from draw import SUPPORTED_CANVAS
```
cly.py:
```
import click
import svgwrite
from math import radians
from PIL import Image
from core import Tree
```
draw.py:
```
from PIL import ImageDraw
from utils import convert_color
import svgwrite
```
